site_name: 面试整理
site_description: 整理和面试有关的资料
site_author: buffalo

# 主题
theme:
  name: material
  language: zh    #语言，可设置多套切换
  icon:
    logo: material/library  #默认logo图标
  features:
    - navigation.tracking  #锚点跟踪
    - navigation.tabs  #导航选项卡
    - content.code.copy # 复制代码按钮
    - content.code.annotate  
    - search.highlight # 搜索高亮
    - search.suggest # 搜索建议
    - navigation.instant.prefetch # 预加载
    - navigation.instant.progress # 进度条
    - navigation.expand # 默认展开导航栏
    - navigation.instant
    - navigation.tabs.sticky # 固定（浏览时不收起）标签
    - navigation.footer # 底部导航栏
    - toc.follow # 目录跟踪-页面右侧的小目录
  palette:     #切换昼夜模式的颜色，审美差就用默认，专业点就自定义    
    primary: teal
    accent: deep orange

# 插件
plugins:
  - search
  - tags


# 扩展
markdown_extensions: # markdown extensions
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - css/extra.css

# 导航设置
nav:
#  - Home: index.md
  - Python:
    - python基础: python/basic.md
    - python进阶: python/advance.md
    - 数据结构和算法: python/datastruct.md
    - 面试:
        - python面试: python/interview/python.md
        - numpy面试: python/interview/numpy.md
        - pandas面试: python/interview/pandas.md
        - 数据处理和分析面试: python/interview/analysis.md
    - 数据处理与分析:
        - numpy: python/numpy.md
        - pandas: python/pandas.md
        - matpliot: python/matpliot.md
        - Seaborn: python/Seaborn.md
    - 标准库:
        - os: python/os.md
        - sys: python/sys.md
        - math: python/math.md
        - datetime: python/datetime.md
        - re: python/re.md
        - shutil: python/shutil.md
        - requests: python/requests.md
        - pathlib: python/pathlib.md
        - pytest: python/pytest.md
        - mock: python/mock.md
        - logging: python/logging.md
        - random: python/random.md
        - time: python/time.md
        - urllib: python/urllib.md
        - json: python/json.md
        - functools: python/functools.md
        - asyncio: python/asyncio.md
        - pickle: python/pickle.md
        - celery: python/celery.md
    - 数据库:
        - sqlalchemy: python/sqlalchemy.md
        - pymysql: python/pymysql.md
        - redis: python/redis.md
    - 爬虫:
        - beautifulsoup: python/beautifulsoup.md
        - scrapy: python/scrapy.md
        - selenium: python/selenium.md
    - 科学计算与机器学习:
        - scipy: python/scipy.md
        - scikit-learn: python/scikit-learn.md
        - pytorch: python/pytorch.md

  - web:
    - django:
        - 基础: webs/django/basic.md
        - restful: webs/django/restful.md
        - 面试: webs/django/interview.md
    - flask:
        - 基础: webs/flask/basic.md
    - fastapi:
        - 基础: webs/fastapi/basic.md
        - 面试: webs/fastapi/interview.md
  
  - 数据库:
    - mysql:
      - sql: database/mysql/sql.md
      - 基础: database/mysql/basic.md
      - 面试: database/mysql/interview.md
      - interview: database/mysql/面试.md
    - redis:
      - 基础: database/redis/basic.md
      - 面试: database/redis/interview.md
    - mongodb:
      - 基础:  database/mongodb/basic.md
      - 面试: database/mongodb/interview.md
    - elastic:
      - 基础: database/elastic/basic.md
      - 面试: database/elastic/interview.md

  - 中间件:
      - kafka:
          - 基础: middlewares/kafka/basic.md
          - 面试: middlewares/kafka/interview.md
      - rabbitmq:
          - 基础: middlewares/rabbitmq/basic.md
          - 面试: middlewares/rabbitmq/interview.md
      - zookeeper:
          - 基础: middlewares/zookeeper/basic.md
          - 面试: middlewares/zookeeper/interview.md
  
  - 服务器:
    - nginx:
      - 基础: server/nginx/basic.md
      - 面试: server/nginx/interview.md
    - uvicorn:
        - 基础: server/uvicorn/basic.md

  - 云原生:
    - docker:
      - 基础: cloud/docker/basic.md
      - 面试: cloud/docker/interview.md
    - kubernetes:
      - 基础: cloud/kubernetes/basic.md
      - 监控和日志: cloud/kubernetes/monitor.md
      - crictl: cloud/kubernetes/crictl.md
      - helm: cloud/kubernetes/helm.md
      - 面试: cloud/kubernetes/interview.md

  - 分布式:
      - 教程: https://juejin.cn/column/7098219195371880484
  - 人工智能:
      - AI:
          - 概念: LLM/ai-basic.md
          - 基础: LLM/AI.md
      - LLM:
          - 基础教程: LLM/basic.md
          - 进阶教程: LLM/advance.md
          - 面试:  LLM/interview.md
          - langchain: LLM/langchain.md


  - 计算机基础:
      - 操作系统: computers/system.md
      - 计算机网络: computers/network.md

  - 系统设计:
      - 面试题: design/basic.md

  


 
  

  
